### ISSUE TITLE
导入中的`songrating`无效

### ISSUE THREAD

**Issue by corvo007** [Yuri-YuzuChaN/Arcaea#1]
如下：
https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L8
此外，这一行也有问题，可能是函数调用写成了字典索引：
https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L168

**Comment by Yuri-YuzuChaN** [comment]
> 如下：
> https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L8
> 
> 
> 此外，这一行也有问题，可能是函数调用写成了字典索引：
> https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L168

这个项目在还没完成时，BOTARCAPI作者已经跑路了，3.6.4的版本改了api，作者已经删档了

**Comment by corvo007** [comment]
> > 如下：
> > https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L8
> > 
> > 此外，这一行也有问题，可能是函数调用写成了字典索引：
> > https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L168
> 
> 这个项目在还没完成时，BOTARCAPI作者已经跑路了，3.6.4的版本改了api，作者已经删档了

所以说这个现在用不了咯？

**Comment by Yuri-YuzuChaN** [comment]
> > > 如下：
> > > https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L8
> > > 
> > > 此外，这一行也有问题，可能是函数调用写成了字典索引：
> > > https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L168
> > 
> > 
> > 这个项目在还没完成时，BOTARCAPI作者已经跑路了，3.6.4的版本改了api，作者已经删档了
> 
> 所以说这个现在用不了咯？

如果之前搭好了botarcapi，主要用于查曲库，我可以上传个只能查recent的版本，就是麻烦点，需要手动添加好友

**Comment by corvo007** [comment]
> > > > 如下：
> > > > https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L8
> > > > 
> > > > 此外，这一行也有问题，可能是函数调用写成了字典索引：
> > > > https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L168
> > > 
> > > 
> > > 这个项目在还没完成时，BOTARCAPI作者已经跑路了，3.6.4的版本改了api，作者已经删档了
> > 
> > 
> > 所以说这个现在用不了咯？
> 
> 如果之前搭好了botarcapi，主要用于查曲库，我可以上传个只能查recent的版本，就是麻烦点，需要手动添加好友

添加好友？用于查询的账号需要和查询者的账号是好友才能查吗？

**Comment by Yuri-YuzuChaN** [comment]
> > > > > 如下：
> > > > > https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L8
> > > > > 
> > > > > 此外，这一行也有问题，可能是函数调用写成了字典索引：
> > > > > https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L168
> > > > 
> > > > 
> > > > 这个项目在还没完成时，BOTARCAPI作者已经跑路了，3.6.4的版本改了api，作者已经删档了
> > > 
> > > 
> > > 所以说这个现在用不了咯？
> > 
> > 
> > 如果之前搭好了botarcapi，主要用于查曲库，我可以上传个只能查recent的版本，就是麻烦点，需要手动添加好友
> 
> 添加好友？用于查询的账号需要和查询者的账号是好友才能查吗？

不需要相互添加，只需要用于查询的账号添加查询者好友就可以使用

**Comment by corvo007** [comment]
> > > > > > 如下：
> > > > > > https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L8
> > > > > > 
> > > > > > 此外，这一行也有问题，可能是函数调用写成了字典索引：
> > > > > > https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L168
> > > > > 
> > > > > 
> > > > > 这个项目在还没完成时，BOTARCAPI作者已经跑路了，3.6.4的版本改了api，作者已经删档了
> > > > 
> > > > 
> > > > 所以说这个现在用不了咯？
> > > 
> > > 
> > > 如果之前搭好了botarcapi，主要用于查曲库，我可以上传个只能查recent的版本，就是麻烦点，需要手动添加好友
> > 
> > 
> > 添加好友？用于查询的账号需要和查询者的账号是好友才能查吗？
> 
> 不需要相互添加，只需要用于查询的账号添加查询者好友就可以使用

明白了，还麻烦您上传一下您这个可以查recent的版本，谢谢。

**Comment by Yuri-YuzuChaN** [comment]
> > > > > > > 如下：
> > > > > > > https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L8
> > > > > > > 
> > > > > > > 此外，这一行也有问题，可能是函数调用写成了字典索引：
> > > > > > > https://github.com/Yuri-YuzuChaN/Arcaea/blob/acdb4c70e5fd8645e6001abad09e66d7331afa9d/draw.py#L168
> > > > > > 
> > > > > > 
> > > > > > 这个项目在还没完成时，BOTARCAPI作者已经跑路了，3.6.4的版本改了api，作者已经删档了
> > > > > 
> > > > > 
> > > > > 所以说这个现在用不了咯？
> > > > 
> > > > 
> > > > 如果之前搭好了botarcapi，主要用于查曲库，我可以上传个只能查recent的版本，就是麻烦点，需要手动添加好友
> > > 
> > > 
> > > 添加好友？用于查询的账号需要和查询者的账号是好友才能查吗？
> > 
> > 
> > 不需要相互添加，只需要用于查询的账号添加查询者好友就可以使用
> 
> 明白了，还麻烦您上传一下您这个可以查recent的版本，谢谢。

新版本已经上传
