### ISSUE TITLE
无法生成arcaea.db（或者说未发现arcaea.db？）

### ISSUE THREAD

**Issue by PigeonMing** [Yuri-YuzuChaN/Arcaea#2]
已尝试在所有可能出现的地方都找过了，都没发现有叫arcaea.db的文件
![image](https://user-images.githubusercontent.com/64831497/135467182-fed59ec5-c3b2-42eb-a4ca-53e43332f783.png)

**Comment by Yuri-YuzuChaN** [comment]
数据库文件在用户文档的.hoshino文件夹
![image](https://user-images.githubusercontent.com/65105396/135467828-ddc122fe-0b0b-46c2-b6c0-8015061a52dd.png)

**Comment by PigeonMing** [comment]
找到了，十分感谢！
