### ISSUE TITLE
arcinfo查询时间过长

### ISSUE THREAD

**Issue by kosakarin** [Yuri-YuzuChaN/Arcaea#3]
在使用过程中发现每次调用arcinfo指令进行查询时，bot都需要数十分钟的时间才会回复结果，而且这个时间正在不断变长，目前需要长达30分钟才会获得结果，请问这个是因为网络的原因吗？
并未对源码进行过修改；
bot部署环境：阿里云服务器，中国上海，双核2M服务器，带宽5Mbps，平时服务器上会挂着FastGithub；

**Comment by Yuri-YuzuChaN** [comment]
技术有限，b30的api用的est的查分器，所以速度慢排队都不可避免

**Comment by kosakarin** [comment]
好的，明白了
